name: Build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4.1.7
      
    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@v5

    - name: Build Project
      uses: threeal/cmake-action@v2.0.0
      with:
        build-dir: out/build
        generator: Ninja
        cxx-compiler: g++-13
        cxx-flags: -std=c++20
        options: CMAKE_BUILD_TYPE=Release
